config/routes.rb
FilmetricRails::Application.routes.draw do
  root 'searches#search'
  get "/about" => 'static#about', as: 'about'

  get '/search' => 'searches#search'
  get '/searches/' => 'searches#show', as: 'searches'

  get '/movies/browse' => 'movies#browse', as: 'browse'
  get '/movies/discover' => 'movies#discover', as: 'discover'
  get '/movies/:id' => 'movies#show', as: 'movie'


  get '/actors/:id' => 'actors#show', as: 'actor'
  get '/directors/:id' => 'directors#show', as: 'director'
  get '/genres/:id' => 'genres#show', as: 'genre'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MoviesHelper

  def show
    @movie = Movie.find(params[:id])
    @release = @movie.release_date.strftime("%B %-e, %Y")
    respond_to do |f|
      f.html { render 'show' }
      f.json { render json: @movie, include: [:actors, :genres, :directors], status: 200 }
    end
  end

  def browse
    @filmetric_evals = options_for_browsing
    @genres = Genre.all.select { |genre| genre.movies.length >= 20 }
    respond_to do |f|
      f.html { render 'browse' }
      f.json { render json: {genres: @genres, filmetricEvals: @filmetric_evals}, status: 200 }
    end
  end

  def discover
    range = retrieve_range_for(params["filmetric_eval"].to_i)
    genre = Genre.find(params["genre"].to_i)
    @choices = find_choices_for(range, genre)
    respond_to do |f|
      f.js
      f.json { render json: @choices, include: [:actors, :genres, :directors], status: 200 }
    end
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def filmetric_responses
    {
      (25..100) => "and critics are a little...too into it!",
      (16..25) => "and critics liked it a lot more!",
      (9..15) => "and critics liked it more.",
      (4..8) => "and critics liked it a little more.",
      (-3..3) => "and everyone likes it equally.",
      (-8..-4) => "and audiences liked it a little more.",
      (-15..-9) => "and audiences liked it more.",
      (-25..-16) => "and audiences liked it a lot more!",
      (-100..-25) => "and audiences are a little...too into it!"
    }
  end

  def browsing_options
    {
      (16..100) => "critics like a lot more",
      (4..15) => "critics like more",
      (-3..3) => "critics and audiences like equally",
      (-15..-4) => "audiences like more",
      (-100..-16) => "audiences like a lot more"
    }
  end

  def options_for_browsing
    indeces = (0..(browsing_options.keys.length-1)).to_a
    responses = browsing_options.values
    indeces.zip(responses)
  end

  def retrieve_range_for(choice)
    browsing_options.keys[choice]
  end

  def find_choices_for(range, genre)
    max = range.max
    min = range.min

    choices = Movie.joins(:genre_movies).where("genre_id = #{genre.id} AND filmetric >= #{min} AND filmetric <= #{max}")
    choices.reject { |choice| choice.poster_link == "http://images.rottentomatoescdn.com/images/redesign/poster_default.gif" }
  end

  def quality_of(movie)
    average = (movie.critics_score + movie.audience_score)/2
    if average > 75
      "good"
    elsif average.between?(50,75)
      "ok"
    elsif average < 50
      "bad"
    end
  end

  def build_overview(movie)
    average = (movie.critics_score + movie.audience_score)/2

    if average > 88
      quality_response = "It’s amazing, "
    elsif average > 75
      quality_response = "It’s damn good, "
    elsif average.between?(50,75)
      quality_response = "It’s decent, "
    elsif average.between?(30,49)
      quality_response = "It’s kind of crap, "
    elsif average.between?(0,29)
      quality_response = "It’s probably crap, "
    end

    filmetric_response = ""

    filmetric_responses.each do |range, phrase|
      if range.include?(movie.filmetric)
        filmetric_response = phrase
      end
    end

    quality_response + filmetric_response
  end
end

app/views/movies/_audience_score.html.erb
<% if @movie.audience_score > 60 %>
  <a class="rt-score" href="<%= @movie.rt_link %>"><%= image_tag("popcorn.png", class: "good-rt-img") %></a>
  <p class="rt-score"><%= @movie.audience_score %>%</p>
<% else %>
  <a class="rt-score" href="<%= @movie.rt_link %>"><%= image_tag("spilled.png", class: "bad-rt-img") %></a>
  <p class="rt-score"><%= @movie.audience_score %>%</p>
<% end %>

app/views/movies/_critic_score.html.erb
<% if @movie.critics_score > 60  %>
  <a class="rt-score" href="<%= @movie.rt_link %>"><%= image_tag("fresh.png", class: "good-rt-img") %></a>
  <p class="rt-score"><%= @movie.critics_score %>% </p>
<% else %>
  <a class="rt-score" href="<%= @movie.rt_link %>"><%= image_tag("rotten.png", class: "bad-rt-img") %></a>
  <p class="rt-score"><%= @movie.critics_score %>% </p>
<% end %>

app/views/movies/_info_box.html.erb
<p>
  Release Date: <%= @release %><br>
  Rating: <%= @movie.rating %><br>
  <% unless @movie.directors.empty? %>
    Directed By: <a href="<%= director_path(@movie.directors.first) %>">
      <%= @movie.directors.first.name %></a>
  <% end %>
</p>

app/views/movies/_options.html.erb
<div class="row" id="movie-options">
  <% if !choices.blank? %>
    <% choices.each do |movie| %>
      <div class="choice">
        <a href="<%= movie_path(movie) %>"><img class="poster-thumbnail" src="<%= movie.poster_link %>"></a>
      </div>
    <% end %>
  <% else %>
    <p id="notice">Sorry, no results were found.</p>
  <% end %>
</div>

app/views/movies/_score_box.html.erb
<div id="score-box">
  <p id="copyright"><strong>Rotten Tomatoes® Scores</strong></p>

  <div id="scores">
    <%= render 'critic_score' %> <span class="math">-</span>
    <%= render 'audience_score' %> <span class="math">=</span>
    <span id="filmetric" class="<%= quality_of(@movie) %>"><%= @movie.filmetric %></span>
  </div>

  <p id="overview"><%= build_overview(@movie) %></p>
</div>

app/views/movies/browse.html.erb
<div class="row">
  <%= render 'layouts/nav' %>
  <div id="search-container">
    <div class="form-group" id="search-box">
        <%= form_tag discover_path, { :method => :get, :class => "form-inline", :remote => true }  do %>
          <p class="browse-form"> I want </p>

          <%= label_tag :genre, "Genre", :class => "sr-only" %>
          <%= select_tag :genre, options_from_collection_for_select(@genres, "id", "name"), :class => "form-control input-lg", :id => "categories"  %>

          <p class="browse-form"> movies that </p>

          <%= label_tag :filmetric_eval, "Flimetric", :class => "sr-only" %>
          <%= select_tag :filmetric_eval, options_from_collection_for_select(@filmetric_evals, "first", "second"), :class => "form-control input-lg", :id => "categories" %><br><br>

          <%= submit_tag "Search", :class => "btn btn-lg btn-primary", :id => "browse-button" %>
        <% end %>
    </div>
  </div>
</div>

app/views/movies/discover.html.erb
<div class="row">
  <div id="movie-options">
    <% i = 0 %>
    <% unless @choices.nil? || @choices.empty? %>
      <% @choices.each do |movie| %>
        <a href="<%= movie_path(movie) %>"><img class="poster-thumbnail" src="<%= movie.poster_link %>"
        style="left: <%= 17 + i %>px;"></a>
        <% i += 250 %>
      <% end %> 
    <% end %>
  </div>
</div>

app/views/movies/discover.js.erb
$("#movie-options").remove();
$("body").append("<%= j render(:partial => 'options', locals: {choices: @choices}) %>");

app/views/movies/show.html.erb
<div class="row">
  <%= render 'layouts/nav' %>

  <div class="col-md-7" id="data-container">
    <h1><%= @movie.title %></h1>

    <%= render 'score_box' %>

    <div id="item-data">
      <h2>Info</h2>
        <%= render 'info_box' %>
      <h2>Genres</h2>
      <ul>
        <%= render @movie.genres %>
      </ul>
      <h2>Actors</h2>
      <ul>
        <%= render @movie.actors %>
      </ul>
    </div>
  </div>

  <div id="poster-container" class="col-md-4">
    <img src="<%= @movie.poster_link %>" class="img-responsive poster">
  </div>
</div>