config/routes.rb
FilmetricRails::Application.routes.draw do
  root 'searches#search'
  get "/about" => 'static#about', as: 'about'

  get '/search' => 'searches#search'
  get '/searches/' => 'searches#show', as: 'searches'

  get '/movies/browse' => 'movies#browse', as: 'browse'
  get '/movies/discover' => 'movies#discover', as: 'discover'
  get '/movies/:id' => 'movies#show', as: 'movie'


  get '/actors/:id' => 'actors#show', as: 'actor'
  get '/directors/:id' => 'directors#show', as: 'director'
  get '/genres/:id' => 'genres#show', as: 'genre'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
  end

  def show
    respond_to do |f|
      if params[:q].empty?
        flash.now[:notice] = "You gotta give me something!"
        f.html { return render "search" }
      end

      query = params[:q].split.collect(&:downcase).join(" ")
      handle_query(params[:category], query, f)
    end
  end

  private

  def handle_query(category, query, f)
    results_from_db = check_database(category, query)
    if results_from_db.blank?
      results_from_rt = check_rt(category, query)
      if results_from_rt.blank?
        flash.now[:notice] = "I'm sorry, nothing matched what you were looking for."
        f.html { render "search" }
        f.json { render json: {}, status: 200 }
      else
        return save_and_display(results_from_rt, query, f)
      end
    end

    @results = specify_query(results_from_db)
    f.json { render json: @results, include: [:actors, :genres, :directors], status: 200 }
    if @results.count == 1
      f.html { redirect_to send("#{category.downcase}_path", results_from_db.first) }
    else
      f.html { render "show" }
    end
  end

  def specify_query(results)
    if params[:actor] && params[:director]
      execute_specified_query(results, 'director', 'actor')
    elsif params[:actor]
      execute_specified_query(results, 'actor')
    elsif params[:director]
      execute_specified_query(results, 'director')
    else
      results
    end
  end

  def execute_specified_query(results, category, extra_category = nil)
    category_class = category.capitalize.constantize
    new_results = results.map { |result|
      name = params[category.to_sym]
      table = category_class.arel_table
      result if result.send(category.pluralize).include?(category_class.where(table[:name].matches("%#{name}%")).first)
    }.compact
    if extra_category == nil
      new_results
    else
      execute_specified_query(new_results, extra_category)
    end
  end

  def check_database(category, query)
    if category == "Movie"
      Movie.where('lower(title) LIKE ?', "%#{query}%")
    else
      category_table = category.constantize.arel_table
      category.constantize.where(category_table[:name].matches("%#{query}%"))
    end
  end

  def check_rt(category, query)
    case category
    when "Movie"
      RTQuerier.find_by_title(query)
    end
  end

  def save_and_display(rt_result, query, f)
    RTQuerier.save_to_db(rt_result)
    @results = Movie.where('lower(title) LIKE ?', "%#{query}%")
    if @results.empty?
      flash.now[:notice] = "I'm sorry, nothing matched what you were looking for."
      f.html { render "search" }
      f.json { render json: {}, status: 200 }
    end
    f.html { redirect_to movie_path(@results.first) if @results.count == 1 }
    f.json { render json: @results, include: [:actors, :genres, :directors], status: 200 }
  end
end

app/views/searches/_film_strip.html.erb
<div id="strip-wrapper">
  <div id="film-strip">
    <% her = Movie.find_by(title: "Her") %>
    <% gravity = Movie.find_by(title: "Gravity") %>
    <% children = Movie.find_by(title: "Children of Men") %>
    <% die = Movie.find_by(title: "Die Hard") %>
    <% avatar = Movie.find_by(title: "Avatar") %>
    <% ghostbusters = Movie.find_by(title: "Ghostbusters") %>
    <% movies = [her, gravity, children, die, avatar, ghostbusters] %>
    <% i = 0 %>

    <% movies.each do |movie| %>
      <a href="<%= movie_path(movie) %>"><img id="poster-thumbnail" src="<%= movie.poster_link %>"
        style="left: <%= 17 + i %>px;"></a>
      <% i += 250 %>
    <% end %>
  </div>
</div>

app/views/searches/search.html.erb
<% flash.each do |level, message| %>
  <div class="<%= flash_class(level) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
      &times;
    </button>
    <%= message %>
  </div>
<% end %>

<div id="search-container">
  <%= render 'layouts/nav' %>

  <div id="row">
      <h1>Filmetric: <br><small>the gap between critics & audience</small></h1>
  </div>

  <div id="row">
    <div class="form-group" id="search-box">
        <%= form_tag searches_path, { :method => :get, :class => "form-inline" }  do %>
          <%= label_tag :category, "Category", :class => "sr-only" %>
          <%= select_tag :category,
            "<option>Movie</option>
             <option>Actor</option>
             <option>Director</option>
             <option>Genre</option>".html_safe, :class => "form-control input-lg", :id => "categories" %>

          <%= label_tag :q, "Search", :class => "sr-only" %>
          <%= text_field_tag :q, "", :class => "form-control input-lg", :autofocus => true %>

          <%= submit_tag "Search", :class => "btn btn-lg btn-primary", :id => "search-button" %>
        <% end %>
    </div>
  </div>

  <div id="row">
    <%#= render 'film_strip' %>
  </div>
</div>

app/views/searches/show.html.erb
<div class="col-md-8" id="results-container">
  <%= render 'layouts/nav' %>

  <h1>Search Results:</h1>

  <ul>
    <% @results.each do |result| %>
      <% if result.is_a? Movie %>
        <li><a href="<%= movie_path(result) %>"><%= result.title %> (<%= result.release_date %>)</a></li>
      <% elsif result.is_a? Actor %>
        <li><a href="<%= actor_path(result) %>"><%= result.name %></a></li>
      <% elsif result.is_a? Director %>
        <li><a href="<%= director_path(result) %>"><%= result.name %></a></li>
      <% elsif result.is_a? Genre %>
        <li><a href="<%= genre_path(result) %>"><%= result.name %></a></li>
      <% end %>
    <% end %>
  </ul>
</div>