config/routes.rb
FilmetricRails::Application.routes.draw do
  root 'searches#search'
  get "/about" => 'static#about', as: 'about'

  get '/search' => 'searches#search'
  get '/searches/' => 'searches#show', as: 'searches'

  get '/movies/browse' => 'movies#browse', as: 'browse'
  get '/movies/discover' => 'movies#discover', as: 'discover'
  get '/movies/:id' => 'movies#show', as: 'movie'


  get '/actors/:id' => 'actors#show', as: 'actor'
  get '/directors/:id' => 'directors#show', as: 'director'
  get '/genres/:id' => 'genres#show', as: 'genre'
end

app/views/layouts/_graph.html.erb
<% data = [].tap do |data| %>
  <% resource.movies.map do |movie| %> 
    <% data << [movie.release_date, movie.filmetric] %>
  <% end %>
<% end %>

<%= line_chart data, library: { tooltip: { trigger: 'none' }, title: "Movies by Filmetric" } %>

app/views/layouts/_movie_list.html.erb
<% @movies.each do |movie| %>
  <% @average = ((movie.critics_score + movie.audience_score) / 2) %>
  <% if @average >= 75 %>
    <li><a class="good" href="<%= movie_path(movie.id) %>"><%= movie.title %> (<%= movie.release_year %>)</a></li>
  <% elsif @average.between?(50,75) %>
    <li><a class="ok" href="<%= movie_path(movie.id) %>"><%= movie.title %> (<%= movie.release_year %>)</a></li>
  <% elsif @average < 50 %>
    <li><a class="bad" href="<%= movie_path(movie.id) %>"><%= movie.title %> (<%= movie.release_year %>)</a></li>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<div id="nav">
    <%= link_to_unless_current "Home", root_path do %>
      <p>Home</p>
    <% end %>
    <%#= link_to_unless_current "Browse", browse_path do %>
      <!-- <p>Browse</p> -->
    <%# end %>
    <%= link_to_unless_current "What the Hell Is This?", about_path do %>
      <p>What the Hell Is This?</p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filmetric</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>